export enum ProductionComplex {
  ElkHills = 'Elk Hills',
  Belridge = 'Belridge',
  Wilmington = 'Wilmington',
  CarbonTerraVault = 'Carbon TerraVault',
  NonOperatingArea = 'Non-Operating Area',
}

export interface ILocation {
  readonly id: string;
  readonly name: string;
  readonly productionComplex: ProductionComplex;
  readonly operatingArea?: string;
  readonly entityName: string;
  readonly fieldManagerSupervisor: string;
  readonly maintenanceSupervisor: string;
  readonly synonyms: string;
  readonly isRegulatedFacility: boolean;
}

// All CRC production locations from Dispatcher Intake Form
export const LOCATIONS: ReadonlyArray<ILocation> = [

  // ── Wilmington Complex ──────────────────────────────────────────
  { id: 'la-basin', name: 'LA BASIN', productionComplex: ProductionComplex.Wilmington, entityName: '', fieldManagerSupervisor: 'JOHNATHON HILL', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'thums-all-locations', name: 'THUMS ALL LOCATIONS', productionComplex: ProductionComplex.Wilmington, entityName: 'THUMS Long Beach Co.', fieldManagerSupervisor: 'JOHNATHON HILL', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'thums-broadway-and-mitchell', name: 'THUMS BROADWAY AND MITCHELL', productionComplex: ProductionComplex.Wilmington, entityName: 'THUMS Long Beach Co.', fieldManagerSupervisor: 'JOSE MARTINEZ', maintenanceSupervisor: 'IGNACIO ARRIZON', synonyms: 'Regulated Facility; PSM', isRegulatedFacility: true },
  { id: 'thums-chaffee', name: 'THUMS CHAFFEE', productionComplex: ProductionComplex.Wilmington, entityName: 'THUMS Long Beach Co.', fieldManagerSupervisor: 'WILL SMITH', maintenanceSupervisor: 'JOHN HASSELMAN', synonyms: '', isRegulatedFacility: false },
  { id: 'thums-drilling-yard', name: 'THUMS DRILLING YARD', productionComplex: ProductionComplex.Wilmington, entityName: 'THUMS Long Beach Co.', fieldManagerSupervisor: 'JASON MENA', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'thums-freeman', name: 'THUMS FREEMAN', productionComplex: ProductionComplex.Wilmington, entityName: 'THUMS Long Beach Co.', fieldManagerSupervisor: 'WILL SMITH', maintenanceSupervisor: 'JOHN HASSELMAN', synonyms: '', isRegulatedFacility: false },
  { id: 'thums-grissom', name: 'THUMS GRISSOM', productionComplex: ProductionComplex.Wilmington, entityName: 'THUMS Long Beach Co.', fieldManagerSupervisor: 'MARCIAL OCHOA', maintenanceSupervisor: 'JOHN HASSELMAN', synonyms: '', isRegulatedFacility: false },
  { id: 'thums-harbor-plaza', name: 'THUMS HARBOR PLAZA', productionComplex: ProductionComplex.Wilmington, entityName: 'THUMS Long Beach Co.', fieldManagerSupervisor: 'DON ADAMS', maintenanceSupervisor: 'IGNACIO ARRIZON', synonyms: '', isRegulatedFacility: false },
  { id: 'thums-pico-leases', name: 'THUMS PICO LEASES', productionComplex: ProductionComplex.Wilmington, entityName: 'THUMS Long Beach Co.', fieldManagerSupervisor: 'DON ADAMS', maintenanceSupervisor: 'IGNACIO ARRIZON', synonyms: '', isRegulatedFacility: false },
  { id: 'thums-pier-g', name: 'THUMS PIER G', productionComplex: ProductionComplex.Wilmington, entityName: 'THUMS Long Beach Co.', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'thums-pier-j', name: 'THUMS PIER J', productionComplex: ProductionComplex.Wilmington, entityName: 'THUMS Long Beach Co.', fieldManagerSupervisor: 'DON ADAMS', maintenanceSupervisor: 'IGNACIO ARRIZON', synonyms: '', isRegulatedFacility: false },
  { id: 'thums-power-plant', name: 'THUMS POWER PLANT', productionComplex: ProductionComplex.Wilmington, entityName: 'THUMS Long Beach Co.', fieldManagerSupervisor: 'JOSE MARTINEZ', maintenanceSupervisor: 'IGNACIO ARRIZON', synonyms: '', isRegulatedFacility: false },
  { id: 'thums-power-plant-ammonia', name: 'THUMS POWER PLANT AMMONIA', productionComplex: ProductionComplex.Wilmington, operatingArea: 'THUMS POWER PLANT', entityName: 'THUMS Long Beach Co.', fieldManagerSupervisor: 'JOSE MARTINEZ', maintenanceSupervisor: 'IGNACIO ARRIZON', synonyms: 'Regulated Facility; CalARP', isRegulatedFacility: true },
  { id: 'thums-warehouse', name: 'THUMS WAREHOUSE', productionComplex: ProductionComplex.Wilmington, entityName: 'THUMS Long Beach Co.', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'thums-white', name: 'THUMS WHITE', productionComplex: ProductionComplex.Wilmington, entityName: 'THUMS Long Beach Co.', fieldManagerSupervisor: 'MARCIAL OCHOA', maintenanceSupervisor: 'JOHN HASSELMAN', synonyms: '', isRegulatedFacility: false },
  { id: 'tidelands-all-locations', name: 'TIDELANDS ALL LOCATIONS', productionComplex: ProductionComplex.Wilmington, entityName: 'Tidelands Oil Production Co.', fieldManagerSupervisor: 'JOHNATHON HILL', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'tidelands-north-operations', name: 'TIDELANDS NORTH OPERATIONS', productionComplex: ProductionComplex.Wilmington, entityName: 'Tidelands Oil Production Co.', fieldManagerSupervisor: 'JASON PERZ', maintenanceSupervisor: 'STEVE GONZALEZ', synonyms: '', isRegulatedFacility: false },
  { id: 'tidelands-south-operations', name: 'TIDELANDS SOUTH OPERATIONS', productionComplex: ProductionComplex.Wilmington, entityName: 'Tidelands Oil Production Co.', fieldManagerSupervisor: 'MATT JOYCE', maintenanceSupervisor: 'STEVE GONZALEZ', synonyms: '', isRegulatedFacility: false },
  { id: 'tidelands-xy-tank-farm', name: 'TIDELANDS XY TANK FARM', productionComplex: ProductionComplex.Wilmington, entityName: 'Tidelands Oil Production Co.', fieldManagerSupervisor: 'JASON PERZ', maintenanceSupervisor: 'STEVE GONZALEZ', synonyms: '', isRegulatedFacility: false },
  { id: 'tidelands-z1-2-tank-farm', name: 'TIDELANDS Z1 2 TANK FARM', productionComplex: ProductionComplex.Wilmington, entityName: 'Tidelands Oil Production Co.', fieldManagerSupervisor: 'MATT JOYCE', maintenanceSupervisor: 'STEVE GONZALEZ', synonyms: '', isRegulatedFacility: false },
  { id: 'tidelands-warehouse', name: 'TIDELANDS WAREHOUSE', productionComplex: ProductionComplex.Wilmington, entityName: 'Tidelands Oil Production Co.', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'hb-emmy-all-locations', name: 'HB EMMY ALL LOCATIONS', productionComplex: ProductionComplex.Wilmington, entityName: 'So Cal Holdings, LLC', fieldManagerSupervisor: 'JOHNATHON HILL', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'huntington-beach', name: 'HUNTINGTON BEACH', productionComplex: ProductionComplex.Wilmington, entityName: 'So Cal Holdings, LLC', fieldManagerSupervisor: 'TERRY JUNKINS', maintenanceSupervisor: 'ALFREDO CHAVEZ', synonyms: '', isRegulatedFacility: false },
  { id: 'hb-gas-plant', name: 'HB GAS PLANT', productionComplex: ProductionComplex.Wilmington, entityName: 'So Cal Holdings, LLC', fieldManagerSupervisor: 'TERRY JUNKINS', maintenanceSupervisor: 'ALFREDO CHAVEZ', synonyms: '', isRegulatedFacility: false },
  { id: 'hb-warehouse', name: 'HB WAREHOUSE', productionComplex: ProductionComplex.Wilmington, entityName: 'So Cal Holdings, LLC', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'platform-emmy', name: 'PLATFORM EMMY', productionComplex: ProductionComplex.Wilmington, entityName: 'So Cal Holdings, LLC', fieldManagerSupervisor: 'TERRY JUNKINS', maintenanceSupervisor: 'ALFREDO CHAVEZ', synonyms: 'Regulated Facility; State Lands', isRegulatedFacility: true },
  { id: 'sacremento-basin', name: 'SACREMENTO BASIN', productionComplex: ProductionComplex.Wilmington, entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'JUSTIN NARUP', maintenanceSupervisor: 'BEN PEARSON', synonyms: '', isRegulatedFacility: false },
  { id: 'grimes', name: 'GRIMES', productionComplex: ProductionComplex.Wilmington, entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'JOVAN AKITAYA', maintenanceSupervisor: 'BEN PEARSON', synonyms: '', isRegulatedFacility: false },
  { id: 'lathrop', name: 'LATHROP', productionComplex: ProductionComplex.Wilmington, entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'JOE CARR', maintenanceSupervisor: 'BEN PEARSON', synonyms: '', isRegulatedFacility: false },
  { id: 'rio-vista', name: 'RIO VISTA', productionComplex: ProductionComplex.Wilmington, entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'JOE CARR', maintenanceSupervisor: 'BEN PEARSON', synonyms: '', isRegulatedFacility: false },
  { id: 'tompkins-hill', name: 'TOMPKINS HILL', productionComplex: ProductionComplex.Wilmington, entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'JOE CARR', maintenanceSupervisor: 'BEN PEARSON', synonyms: '', isRegulatedFacility: false },
  { id: 'willows', name: 'WILLOWS', productionComplex: ProductionComplex.Wilmington, entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'JOVAN AKITAYA', maintenanceSupervisor: 'BEN PEARSON', synonyms: '', isRegulatedFacility: false },
  { id: 'ventura', name: 'VENTURA', productionComplex: ProductionComplex.Wilmington, entityName: 'Aera Energy, LLC', fieldManagerSupervisor: 'ERIN LARNER', maintenanceSupervisor: 'NICK CASTANON', synonyms: 'Legacy Aera', isRegulatedFacility: false },
  { id: 'ventura-gas-plant-6', name: 'VENTURA GAS PLANT 6', productionComplex: ProductionComplex.Wilmington, entityName: 'Aera Energy, LLC', fieldManagerSupervisor: 'JERE DIETZ', maintenanceSupervisor: 'NICK CASTANON', synonyms: 'Regulated Facility; PSM; EPA RMP; CalARP; Legacy Aera', isRegulatedFacility: true },
  { id: 'ventura-gas-plant-7', name: 'VENTURA GAS PLANT 7', productionComplex: ProductionComplex.Wilmington, entityName: 'Aera Energy, LLC', fieldManagerSupervisor: 'JERE DIETZ', maintenanceSupervisor: 'NICK CASTANON', synonyms: 'Regulated Facility; PSM; EPA RMP; CalARP; Legacy Aera', isRegulatedFacility: true },
  { id: 'newport-banning-ranch', name: 'NEWPORT BANNING RANCH', productionComplex: ProductionComplex.Wilmington, entityName: 'Aera Energy, LLC', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },

  // ── Elk Hills Complex ──────────────────────────────────────────
  { id: 'geha', name: 'GEHA', productionComplex: ProductionComplex.ElkHills, entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'LEON SINDEN', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'buena-vista-hills', name: 'BUENA VISTA HILLS', productionComplex: ProductionComplex.ElkHills, operatingArea: 'GEHA', entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'JEREMY SOLF', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'buena-vista-nose', name: 'BUENA VISTA NOSE', productionComplex: ProductionComplex.ElkHills, operatingArea: 'GEHA', entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'JEREMY SOLF', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'elk-hills-35r-cogen', name: 'ELK HILLS 35R COGEN', productionComplex: ProductionComplex.ElkHills, operatingArea: 'GEHA', entityName: 'Elk Hills Power, LLC', fieldManagerSupervisor: 'WELDEN MAYO', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'elk-hills-35r-cogen-ammonia', name: 'ELK HILLS 35R COGEN AMMONIA', productionComplex: ProductionComplex.ElkHills, operatingArea: 'GEHA', entityName: 'Elk Hills Power, LLC', fieldManagerSupervisor: 'WELDEN MAYO', maintenanceSupervisor: '', synonyms: 'Regulated Facility; PSM; EPA RMP; CalARP', isRegulatedFacility: true },
  { id: 'elk-hills-35r-storage-and-loading', name: 'ELK HILLS 35R STORAGE AND LOADING', productionComplex: ProductionComplex.ElkHills, operatingArea: 'GEHA', entityName: 'Elk Hills Power, LLC', fieldManagerSupervisor: 'WELDEN MAYO', maintenanceSupervisor: '', synonyms: 'Regulated Facility; PSM; EPA RMP; CalARP', isRegulatedFacility: true },
  { id: 'elk-hills-all-regulated-facilities', name: 'ELK HILLS ALL REGULATED FACILITIES', productionComplex: ProductionComplex.ElkHills, operatingArea: 'GEHA', entityName: 'Elk Hills Power, LLC', fieldManagerSupervisor: 'BRANDON MYERS', maintenanceSupervisor: '', synonyms: 'Regulated Facility; PSM; EPA RMP; CalARP', isRegulatedFacility: true },
  { id: 'elk-hills-cgp1', name: 'ELK HILLS CGP1', productionComplex: ProductionComplex.ElkHills, operatingArea: 'GEHA', entityName: 'Elk Hills Power, LLC', fieldManagerSupervisor: 'WELDEN MAYO', maintenanceSupervisor: '', synonyms: 'Regulated Facility; PSM; EPA RMP; CalARP', isRegulatedFacility: true },
  { id: 'elk-hills-east', name: 'ELK HILLS EAST', productionComplex: ProductionComplex.ElkHills, operatingArea: 'GEHA', entityName: 'Elk Hills Power, LLC', fieldManagerSupervisor: 'JOHN GOLDMAN', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'elk-hills-gtu2', name: 'ELK HILLS GTU2', productionComplex: ProductionComplex.ElkHills, operatingArea: 'GEHA', entityName: 'Elk Hills Power, LLC', fieldManagerSupervisor: 'WELDEN MAYO', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'elk-hills-hpi', name: 'ELK HILLS HPI', productionComplex: ProductionComplex.ElkHills, operatingArea: 'GEHA', entityName: 'Elk Hills Power, LLC', fieldManagerSupervisor: 'WELDEN MAYO', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'elk-hills-lts1', name: 'ELK HILLS LTS1', productionComplex: ProductionComplex.ElkHills, operatingArea: 'GEHA', entityName: 'Elk Hills Power, LLC', fieldManagerSupervisor: 'WELDEN MAYO', maintenanceSupervisor: '', synonyms: 'Regulated Facility; PSM; EPA RMP; CalARP', isRegulatedFacility: true },
  { id: 'elk-hills-lts2', name: 'ELK HILLS LTS2', productionComplex: ProductionComplex.ElkHills, operatingArea: 'GEHA', entityName: 'Elk Hills Power, LLC', fieldManagerSupervisor: 'WELDEN MAYO', maintenanceSupervisor: '', synonyms: 'Regulated Facility; PSM; EPA RMP; CalARP', isRegulatedFacility: true },
  { id: 'elk-hills-power', name: 'ELK HILLS POWER', productionComplex: ProductionComplex.ElkHills, operatingArea: 'GEHA', entityName: 'Elk Hills Power, LLC', fieldManagerSupervisor: 'DANIEL AYALA', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'elk-hills-power-ammonia', name: 'ELK HILLS POWER AMMONIA', productionComplex: ProductionComplex.ElkHills, operatingArea: 'GEHA', entityName: 'Elk Hills Power, LLC', fieldManagerSupervisor: 'DANIEL AYALA', maintenanceSupervisor: '', synonyms: 'Regulated Facility; CalARP', isRegulatedFacility: true },
  { id: 'elk-hills-usds', name: 'ELK HILLS USDS', productionComplex: ProductionComplex.ElkHills, operatingArea: 'GEHA', entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'WELDEN MAYO', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'elk-hills-west', name: 'ELK HILLS WEST', productionComplex: ProductionComplex.ElkHills, operatingArea: 'GEHA', entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'MIKE CARR', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'central-valley', name: 'CENTRAL VALLEY', productionComplex: ProductionComplex.ElkHills, entityName: 'California Resources Production Corporation', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'ant-hill', name: 'ANT HILL', productionComplex: ProductionComplex.ElkHills, operatingArea: 'CENTRAL VALLEY', entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'BRADLEY TUCK', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'bowerbank', name: 'BOWERBANK', productionComplex: ProductionComplex.ElkHills, operatingArea: 'CENTRAL VALLEY', entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'BRADLEY TUCK', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'chico-martinez', name: 'CHICO MARTINEZ', productionComplex: ProductionComplex.ElkHills, operatingArea: 'CENTRAL VALLEY', entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'BRADLEY TUCK', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'mwss-35z', name: 'MWSS 35Z', productionComplex: ProductionComplex.ElkHills, operatingArea: 'CENTRAL VALLEY', entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'BRADLEY TUCK', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'oxnard', name: 'OXNARD', productionComplex: ProductionComplex.ElkHills, operatingArea: 'CENTRAL VALLEY', entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'BRADLEY TUCK', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'rose', name: 'ROSE', productionComplex: ProductionComplex.ElkHills, operatingArea: 'CENTRAL VALLEY', entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'BRADLEY TUCK', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'semitropic', name: 'SEMITROPIC', productionComplex: ProductionComplex.ElkHills, operatingArea: 'CENTRAL VALLEY', entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'BRADLEY TUCK', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'shafter-north', name: 'SHAFTER NORTH', productionComplex: ProductionComplex.ElkHills, operatingArea: 'CENTRAL VALLEY', entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'BRADLEY TUCK', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'south-valley', name: 'SOUTH VALLEY', productionComplex: ProductionComplex.ElkHills, entityName: 'California Resources Production Corporation', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'coles-levee-north', name: 'COLES LEVEE NORTH', productionComplex: ProductionComplex.ElkHills, operatingArea: 'SOUTH VALLEY', entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'SCOTT LAMB', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'coles-levee-south', name: 'COLES LEVEE SOUTH', productionComplex: ProductionComplex.ElkHills, operatingArea: 'SOUTH VALLEY', entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'SCOTT LAMB', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'landslide', name: 'LANDSLIDE', productionComplex: ProductionComplex.ElkHills, operatingArea: 'SOUTH VALLEY', entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'SCOTT LAMB', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'paloma', name: 'PALOMA', productionComplex: ProductionComplex.ElkHills, operatingArea: 'SOUTH VALLEY', entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'SCOTT LAMB', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'pleito-creek', name: 'PLEITO CREEK', productionComplex: ProductionComplex.ElkHills, operatingArea: 'SOUTH VALLEY', entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'SCOTT LAMB', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'pleito-ranch', name: 'PLEITO RANCH', productionComplex: ProductionComplex.ElkHills, operatingArea: 'SOUTH VALLEY', entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'SCOTT LAMB', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'rio-viejo', name: 'RIO VIEJO', productionComplex: ProductionComplex.ElkHills, operatingArea: 'SOUTH VALLEY', entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'SCOTT LAMB', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'san-emidio-nose', name: 'SAN EMIDIO NOSE', productionComplex: ProductionComplex.ElkHills, operatingArea: 'SOUTH VALLEY', entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'SCOTT LAMB', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'tejon', name: 'TEJON', productionComplex: ProductionComplex.ElkHills, operatingArea: 'SOUTH VALLEY', entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'SCOTT LAMB', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'tejon-north', name: 'TEJON NORTH', productionComplex: ProductionComplex.ElkHills, operatingArea: 'SOUTH VALLEY', entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'SCOTT LAMB', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'wheeler-ridge', name: 'WHEELER RIDGE', productionComplex: ProductionComplex.ElkHills, operatingArea: 'SOUTH VALLEY', entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'SCOTT LAMB', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'yowlumne', name: 'YOWLUMNE', productionComplex: ProductionComplex.ElkHills, operatingArea: 'SOUTH VALLEY', entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'SCOTT LAMB', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'thermal', name: 'THERMAL', productionComplex: ProductionComplex.ElkHills, entityName: 'California Resources Production Corporation', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'kern-front', name: 'KERN FRONT', productionComplex: ProductionComplex.ElkHills, operatingArea: 'THERMAL', entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'DANNY TARKINGTON', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'mount-poso', name: 'MOUNT POSO', productionComplex: ProductionComplex.ElkHills, operatingArea: 'THERMAL', entityName: 'California Resources Production Corporation', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'ca-east-bry', name: 'CA EAST (BRY)', productionComplex: ProductionComplex.ElkHills, entityName: '', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'poso-creek-bry', name: 'POSO CREEK (BRY)', productionComplex: ProductionComplex.ElkHills, entityName: 'Berry Petroleum', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'round-mountain-bry', name: 'ROUND MOUNTAIN (BRY)', productionComplex: ProductionComplex.ElkHills, entityName: 'Macpherson Operating Company, L.P.', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'round-mountain-north-bry', name: 'ROUND MOUNTAIN NORTH (BRY)', productionComplex: ProductionComplex.ElkHills, entityName: 'Macpherson Operating Company, L.P.', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'round-mountain-east-bry', name: 'ROUND MOUNTAIN EAST (BRY)', productionComplex: ProductionComplex.ElkHills, entityName: 'Macpherson Operating Company, L.P.', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'mount-poso-bry', name: 'MOUNT POSO (BRY)', productionComplex: ProductionComplex.ElkHills, entityName: 'Berry Petroleum', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'utah-bry', name: 'UTAH (BRY)', productionComplex: ProductionComplex.ElkHills, entityName: 'Berry Petroleum', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'brundage-canyon-gas-plant-bry', name: 'BRUNDAGE CANYON GAS PLANT (BRY)', productionComplex: ProductionComplex.ElkHills, entityName: 'Berry Petroleum', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },

  // ── Belridge Complex ──────────────────────────────────────────
  { id: 'antelope-hills-north', name: 'ANTELOPE HILLS NORTH', productionComplex: ProductionComplex.Belridge, entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'BRETT OTTERNESS', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'belgian-anticline', name: 'BELGIAN ANTICLINE', productionComplex: ProductionComplex.Belridge, entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'BRETT OTTERNESS', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'belridge', name: 'BELRIDGE', productionComplex: ProductionComplex.Belridge, entityName: 'Aera Energy, LLC', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: 'Legacy Aera', isRegulatedFacility: false },
  { id: 'belridge-cogen-32-ammonia', name: 'BELRIDGE COGEN 32 AMMONIA', productionComplex: ProductionComplex.Belridge, entityName: 'Aera Energy, LLC', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: 'Legacy Aera', isRegulatedFacility: false },
  { id: 'belridge-energy', name: 'BELRIDGE ENERGY', productionComplex: ProductionComplex.Belridge, entityName: 'Aera Energy, LLC', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'belridge-facilities', name: 'BELRIDGE FACILITIES', productionComplex: ProductionComplex.Belridge, entityName: 'Aera Energy, LLC', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'belridge-wells', name: 'BELRIDGE WELLS', productionComplex: ProductionComplex.Belridge, entityName: 'Aera Energy, LLC/California Resources Corporation (Confirm with HSE)', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'belridge-south', name: 'BELRIDGE SOUTH', productionComplex: ProductionComplex.Belridge, entityName: 'Aera Energy, LLC/California Resources Corporation (Confirm with HSE)', fieldManagerSupervisor: 'BRETT OTTERNESS', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'coalinga', name: 'COALINGA', productionComplex: ProductionComplex.Belridge, entityName: '', fieldManagerSupervisor: 'JOHN (EVAN) MORONES', maintenanceSupervisor: '', synonyms: 'Legacy Aera', isRegulatedFacility: false },
  { id: 'coalinga-cogen-ammonia', name: 'COALINGA COGEN AMMONIA', productionComplex: ProductionComplex.Belridge, entityName: 'Aera Energy, LLC', fieldManagerSupervisor: 'JOHN (EVAN) MORONES', maintenanceSupervisor: '', synonyms: 'Legacy Aera', isRegulatedFacility: false },
  { id: 'devils-den', name: 'DEVILS DEN', productionComplex: ProductionComplex.Belridge, entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'BRETT OTTERNESS', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'helm', name: 'HELM', productionComplex: ProductionComplex.Belridge, entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'JOHN (EVAN) MORONES', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'kettleman-gas-plant', name: 'KETTLEMAN GAS PLANT', productionComplex: ProductionComplex.Belridge, entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'JOHN (EVAN) MORONES', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'kettleman-north-dome', name: 'KETTLEMAN NORTH DOME', productionComplex: ProductionComplex.Belridge, entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'JOHN (EVAN) MORONES', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'lost-hills', name: 'LOST HILLS', productionComplex: ProductionComplex.Belridge, entityName: '', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: 'Legacy Aera', isRegulatedFacility: false },
  { id: 'lost-hills-cogen-13-ammonia', name: 'LOST HILLS COGEN 13 AMMONIA', productionComplex: ProductionComplex.Belridge, entityName: 'Aera Energy, LLC', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: 'Legacy Aera', isRegulatedFacility: false },
  { id: 'lost-hills-energy', name: 'LOST HILLS ENERGY', productionComplex: ProductionComplex.Belridge, entityName: 'Aera Energy, LLC', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'lost-hills-facilities', name: 'LOST HILLS FACILITIES', productionComplex: ProductionComplex.Belridge, entityName: 'Aera Energy, LLC', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'lost-hills-wells', name: 'LOST HILLS WELLS', productionComplex: ProductionComplex.Belridge, entityName: 'Aera Energy, LLC', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'mcdonald-anticline', name: 'MCDONALD ANTICLINE', productionComplex: ProductionComplex.Belridge, entityName: 'Aera Energy, LLC/California Resources Corporation (Confirm with HSE)', fieldManagerSupervisor: 'BRETT OTTERNESS', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'mckittrick', name: 'MCKITTRICK', productionComplex: ProductionComplex.Belridge, entityName: 'Aera Energy, LLC/California Resources Corporation (Confirm with HSE)', fieldManagerSupervisor: 'BRETT OTTERNESS', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'midway-sunset', name: 'MIDWAY SUNSET', productionComplex: ProductionComplex.Belridge, entityName: 'Aera Energy, LLC/California Resources Corporation (Confirm with HSE)', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: 'Legacy Aera', isRegulatedFacility: false },
  { id: 'midway-sunset-energy', name: 'MIDWAY SUNSET ENERGY', productionComplex: ProductionComplex.Belridge, entityName: 'Aera Energy, LLC/California Resources Corporation (Confirm with HSE)', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: 'Legacy Aera', isRegulatedFacility: false },
  { id: 'midway-sunset-facilities', name: 'MIDWAY SUNSET FACILITIES', productionComplex: ProductionComplex.Belridge, entityName: 'Aera Energy, LLC/California Resources Corporation (Confirm with HSE)', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'midway-sunset-wells', name: 'MIDWAY SUNSET WELLS', productionComplex: ProductionComplex.Belridge, entityName: 'Aera Energy, LLC/California Resources Corporation (Confirm with HSE)', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'raisin-city', name: 'RAISIN CITY', productionComplex: ProductionComplex.Belridge, entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'JOHN (EVAN) MORONES', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'riverdale', name: 'RIVERDALE', productionComplex: ProductionComplex.Belridge, entityName: 'California Resources Production Corporation', fieldManagerSupervisor: 'JOHN (EVAN) MORONES', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'san-ardo', name: 'SAN ARDO', productionComplex: ProductionComplex.Belridge, entityName: 'Aera Energy, LLC', fieldManagerSupervisor: 'BRETT BANE', maintenanceSupervisor: '', synonyms: 'Legacy Aera', isRegulatedFacility: false },
  { id: 'san-ardo-cogen-ammonia', name: 'SAN ARDO COGEN AMMONIA', productionComplex: ProductionComplex.Belridge, entityName: 'Aera Energy, LLC', fieldManagerSupervisor: 'BRETT BANE', maintenanceSupervisor: '', synonyms: 'Legacy Aera', isRegulatedFacility: false },
  { id: 'san-ardo-trucking-facility', name: 'SAN ARDO TRUCKING FACILITY', productionComplex: ProductionComplex.Belridge, entityName: 'Aera Energy, LLC', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'ca-west-bry', name: 'CA WEST (BRY)', productionComplex: ProductionComplex.Belridge, entityName: '', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'north-midway-sunset-bry', name: 'NORTH MIDWAY SUNSET (BRY)', productionComplex: ProductionComplex.Belridge, entityName: 'Berry Petroleum', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: '21z-cogen-ammonia-bry', name: '21Z COGEN AMMONIA (BRY)', productionComplex: ProductionComplex.Belridge, operatingArea: 'NORTH MIDWAY SUNSET (BRY)', entityName: 'Berry Petroleum', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'pan-fee-cogen-ammonia-bry', name: 'PAN FEE COGEN AMMONIA (BRY)', productionComplex: ProductionComplex.Belridge, operatingArea: 'NORTH MIDWAY SUNSET (BRY)', entityName: 'Berry Petroleum', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'south-belridge-bry', name: 'SOUTH BELRIDGE (BRY)', productionComplex: ProductionComplex.Belridge, entityName: 'Berry Petroleum', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'south-midway-sunset-bry', name: 'SOUTH MIDWAY SUNSET (BRY)', productionComplex: ProductionComplex.Belridge, entityName: 'Berry Petroleum', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'cogen-18-ammonia-bry', name: 'COGEN 18 AMMONIA (BRY)', productionComplex: ProductionComplex.Belridge, operatingArea: 'SOUTH MIDWAY SUNSET (BRY)', entityName: 'Berry Petroleum', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'cogen-38-ammonia-bry', name: 'COGEN 38 AMMONIA (BRY)', productionComplex: ProductionComplex.Belridge, operatingArea: 'SOUTH MIDWAY SUNSET (BRY)', entityName: 'Berry Petroleum', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },

  // ── Carbon TerraVault ──────────────────────────────────────────
  { id: 'cal-capture', name: 'CAL CAPTURE', productionComplex: ProductionComplex.CarbonTerraVault, entityName: '', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'ctv-1', name: 'CTV 1', productionComplex: ProductionComplex.CarbonTerraVault, entityName: '', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'ctv-jv', name: 'CTV JV', productionComplex: ProductionComplex.CarbonTerraVault, entityName: '', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },

  // ── Non-Operating Area ──────────────────────────────────────────
  { id: '11g-office', name: '11G OFFICE', productionComplex: ProductionComplex.NonOperatingArea, entityName: 'California Resources Production Corporation', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: '18g-warehouse', name: '18G WAREHOUSE', productionComplex: ProductionComplex.NonOperatingArea, entityName: 'California Resources Production Corporation', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'ccf-office', name: 'CCF OFFICE', productionComplex: ProductionComplex.NonOperatingArea, entityName: 'California Resources Production Corporation', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'ming-office', name: 'MING OFFICE', productionComplex: ProductionComplex.NonOperatingArea, entityName: 'California Resources Production Corporation', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'oaks-office', name: 'OAKS OFFICE', productionComplex: ProductionComplex.NonOperatingArea, entityName: 'California Resources Production Corporation', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: 'Legacy Aera', isRegulatedFacility: false },
  { id: 'oasis-office', name: 'OASIS OFFICE', productionComplex: ProductionComplex.NonOperatingArea, entityName: 'California Resources Production Corporation', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: 'Legacy Aera', isRegulatedFacility: false },
  { id: 'sacramento-office', name: 'SACRAMENTO OFFICE', productionComplex: ProductionComplex.NonOperatingArea, entityName: 'California Resources Production Corporation', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'santa-clarita-office', name: 'SANTA CLARITA OFFICE', productionComplex: ProductionComplex.NonOperatingArea, entityName: 'California Resources Production Corporation', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
  { id: 'wtc-office', name: 'WTC OFFICE', productionComplex: ProductionComplex.NonOperatingArea, entityName: 'California Resources Production Corporation', fieldManagerSupervisor: '', maintenanceSupervisor: '', synonyms: '', isRegulatedFacility: false },
];

export function getLocationsByComplex(complex: ProductionComplex): ReadonlyArray<ILocation> {
  return LOCATIONS.filter((loc) => loc.productionComplex === complex);
}

export function getLocationById(id: string): ILocation | undefined {
  return LOCATIONS.find((loc) => loc.id === id);
}
